//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSourceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidatos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidatos()
        {
            this.Experiencia = new HashSet<Experiencia>();
            this.Capacitaciones = new HashSet<Capacitaciones>();
        }
    
        public int Id { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public int IdPuesto { get; set; }
        public int IdDepartamento { get; set; }
        public Nullable<decimal> Salario_Asp { get; set; }
        public string Competencias { get; set; }
        public string Recomendado_p { get; set; }
        public string Estado { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Puestos Puestos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Experiencia> Experiencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Capacitaciones> Capacitaciones { get; set; }
    }
}
