//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSourceWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Capacitaciones
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string Nivel { get; set; }
        public Nullable<System.DateTime> Fecha_desde { get; set; }
        public Nullable<System.DateTime> Fecha_hasta { get; set; }
        public string Institucion { get; set; }
        public Nullable<int> CandidatoId { get; set; }
        [ForeignKey("CandidatoId")]
        public virtual Candidatos Candidatos { get; set; }
    }
}
